import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="de">
      <body>
      <nav>
        <Link href="/">Home</Link> |{" "}
        <Link href="/about">About</Link> |{" "}
        <Link href="/projects">Projects</Link>
      </nav>
      <main>{children}</main>
      </body>
      </html>
  );
}
